### ISSUE TITLE
Feature: Criação dos pacotes MVC

### ISSUE THREAD

**Issue by josecls** [josecls/agripluvi-api#1]
### Descrição
A estruturação que iremos utilizar é o MVC, portanto deve-se criar os pacotes referentes aos pontos:
- Model
- Controller
- Repository

**Obs: não há necessidade de criação de package referente a view em nosso contexto.**

**Comment by josecls** [comment]
@leohas @alecastrovisk @JonatanLessa acredito que a criação `packages` no Java não são consideradas `changes` para o github, pois aparentemente não gera adição de arquivo novo ou mudança de arquivo.

Alguém sabe sobre isso?

**Comment by leohas** [comment]
Sim, só o pacote fica vazio, teria que adicionar uma entidade nele. Acho que tu pode adicionar sei la, um documento de texto por enquanto, qualquer coisa
